services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spimex_web
    ports:
      - "8000:8000"
    environment:
      - ${DB_URL}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - .:/src

  db:
    image: postgres:16
    container_name: spimex_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spimex
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: spimex_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
